services:
  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_SERVICE_URL_BASE=${DATA_SERVICE_URL_BASE}
    volumes:
      - ./backend:/app
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
  cloudflared:
    image: cloudflare/cloudflared:latest
    # Tell cloudflared to point to our Vue frontend dev server
    command: tunnel --url http://frontend:5173 --protocol http2
    restart: unless-stopped
    depends_on:
      - frontend