"""add discussion score to student submissions

Revision ID: 153f8dca530a
Revises: 2a91b6ba3fd0
Create Date: 2026-04-26 11:17:43.915353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153f8dca530a'
down_revision: Union[str, Sequence[str], None] = '2a91b6ba3fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_submissions', sa.Column('discussion_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_submissions', 'discussion_score')
    # ### end Alembic commands ###
