"""add submission_id session anchor to interactions

Revision ID: 4b1143bee86e
Revises: 1914ff5c3ac7
Create Date: 2026-04-26 15:32:49.240101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1143bee86e'
down_revision: Union[str, Sequence[str], None] = '1914ff5c3ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_comments', sa.Column('submission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interaction_comments', 'student_submissions', ['submission_id'], ['id'], ondelete='RESTRICT')
    op.add_column('interaction_likes', sa.Column('submission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interaction_likes', 'student_submissions', ['submission_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interaction_likes', type_='foreignkey')
    op.drop_column('interaction_likes', 'submission_id')
    op.drop_constraint(None, 'interaction_comments', type_='foreignkey')
    op.drop_column('interaction_comments', 'submission_id')
    # ### end Alembic commands ###
