"""add_media_table

Revision ID: 4cd51e561f82
Revises: 31200d583fb8
Create Date: 2026-04-04 13:55:38.034067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd51e561f82'
down_revision: Union[str, Sequence[str], None] = '31200d583fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fid', sa.String(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_fid'), 'media', ['fid'], unique=True)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_media_fid'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
