"""add_users_table_and_tenant_relations

Revision ID: 8e097a3f9efb
Revises: 2af4428414f0
Create Date: 2026-04-01 03:50:10.823533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e097a3f9efb'
down_revision: Union[str, Sequence[str], None] = '2af4428414f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('questions', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('questions', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'users', ['owner_id'], ['id'])
    op.add_column('students', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'users', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'teacher_id')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'owner_id')
    op.drop_column('questions', 'is_public')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
