"""add soft delete, lock and archive states, and social interaction models

Revision ID: b19d8d5b233d
Revises: d8fadf274ef3
Create Date: 2026-04-16 05:57:54.466367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19d8d5b233d'
down_revision: Union[str, Sequence[str], None] = 'd8fadf274ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(), nullable=True),
    sa.CheckConstraint('(CASE WHEN student_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN user_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN guest_name IS NOT NULL THEN 1 ELSE 0 END) = 1', name='interaction_comments_single_author_check'),
    sa.ForeignKeyConstraint(['answer_id'], ['student_answers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_comments_deleted_at'), 'interaction_comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_interaction_comments_id'), 'interaction_comments', ['id'], unique=False)
    op.create_table('interaction_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(), nullable=True),
    sa.CheckConstraint('(CASE WHEN answer_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN comment_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='interaction_likes_single_target_check'),
    sa.CheckConstraint('(CASE WHEN student_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN user_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN guest_name IS NOT NULL THEN 1 ELSE 0 END) = 1', name='interaction_likes_single_author_check'),
    sa.ForeignKeyConstraint(['answer_id'], ['student_answers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['comment_id'], ['interaction_comments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_likes_deleted_at'), 'interaction_likes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_interaction_likes_id'), 'interaction_likes', ['id'], unique=False)
    op.add_column('answer_grading_histories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_answer_grading_histories_deleted_at'), 'answer_grading_histories', ['deleted_at'], unique=False)
    op.drop_constraint(op.f('answer_grading_histories_answer_id_fkey'), 'answer_grading_histories', type_='foreignkey')
    op.drop_constraint(op.f('answer_grading_histories_teacher_id_fkey'), 'answer_grading_histories', type_='foreignkey')
    op.create_foreign_key(None, 'answer_grading_histories', 'student_answers', ['answer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'answer_grading_histories', 'users', ['teacher_id'], ['id'], ondelete='RESTRICT')
    op.add_column('exam_questions', sa.Column('allow_peer_review', sa.Boolean(), nullable=True))
    op.add_column('exam_questions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_exam_questions_deleted_at'), 'exam_questions', ['deleted_at'], unique=False)
    op.drop_constraint(op.f('exam_questions_question_id_fkey'), 'exam_questions', type_='foreignkey')
    op.drop_constraint(op.f('exam_questions_exam_id_fkey'), 'exam_questions', type_='foreignkey')
    op.create_foreign_key(None, 'exam_questions', 'questions', ['question_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'exam_questions', 'exams', ['exam_id'], ['id'], ondelete='RESTRICT')
    op.add_column('exams', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('exams', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('exams', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_exams_deleted_at'), 'exams', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_exams_is_archived'), 'exams', ['is_archived'], unique=False)
    op.create_index(op.f('ix_exams_is_locked'), 'exams', ['is_locked'], unique=False)
    op.drop_constraint(op.f('exams_owner_id_fkey'), 'exams', type_='foreignkey')
    op.create_foreign_key(None, 'exams', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    op.add_column('media', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_media_deleted_at'), 'media', ['deleted_at'], unique=False)
    op.drop_constraint(op.f('media_uploader_id_fkey'), 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'users', ['uploader_id'], ['id'], ondelete='RESTRICT')
    op.add_column('questions', sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('questions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_questions_deleted_at'), 'questions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_questions_is_locked'), 'questions', ['is_locked'], unique=False)
    op.drop_constraint(op.f('questions_owner_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    op.add_column('student_answers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_student_answers_deleted_at'), 'student_answers', ['deleted_at'], unique=False)
    op.drop_constraint(op.f('student_answers_submission_id_fkey'), 'student_answers', type_='foreignkey')
    op.drop_constraint(op.f('student_answers_question_id_fkey'), 'student_answers', type_='foreignkey')
    op.drop_constraint(op.f('student_answers_exam_id_fkey'), 'student_answers', type_='foreignkey')
    op.create_foreign_key(None, 'student_answers', 'questions', ['question_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'student_answers', 'exams', ['exam_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'student_answers', 'student_submissions', ['submission_id'], ['id'], ondelete='RESTRICT')
    op.add_column('student_submissions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_student_submissions_deleted_at'), 'student_submissions', ['deleted_at'], unique=False)
    op.drop_constraint(op.f('student_submissions_student_id_fkey'), 'student_submissions', type_='foreignkey')
    op.drop_constraint(op.f('student_submissions_exam_id_fkey'), 'student_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'student_submissions', 'exams', ['exam_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'student_submissions', 'students', ['student_id'], ['id'], ondelete='RESTRICT')
    op.add_column('students', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_students_deleted_at'), 'students', ['deleted_at'], unique=False)
    op.drop_constraint(op.f('students_teacher_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['teacher_id'], ['id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_teacher_id_fkey'), 'students', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_students_deleted_at'), table_name='students')
    op.drop_column('students', 'deleted_at')
    op.drop_constraint(None, 'student_submissions', type_='foreignkey')
    op.drop_constraint(None, 'student_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('student_submissions_exam_id_fkey'), 'student_submissions', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_submissions_student_id_fkey'), 'student_submissions', 'students', ['student_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_student_submissions_deleted_at'), table_name='student_submissions')
    op.drop_column('student_submissions', 'deleted_at')
    op.drop_constraint(None, 'student_answers', type_='foreignkey')
    op.drop_constraint(None, 'student_answers', type_='foreignkey')
    op.drop_constraint(None, 'student_answers', type_='foreignkey')
    op.create_foreign_key(op.f('student_answers_exam_id_fkey'), 'student_answers', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_answers_question_id_fkey'), 'student_answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_answers_submission_id_fkey'), 'student_answers', 'student_submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_student_answers_deleted_at'), table_name='student_answers')
    op.drop_column('student_answers', 'deleted_at')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_owner_id_fkey'), 'questions', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_questions_is_locked'), table_name='questions')
    op.drop_index(op.f('ix_questions_deleted_at'), table_name='questions')
    op.drop_column('questions', 'deleted_at')
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    op.drop_column('questions', 'is_locked')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key(op.f('media_uploader_id_fkey'), 'media', 'users', ['uploader_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_media_deleted_at'), table_name='media')
    op.drop_column('media', 'deleted_at')
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.create_foreign_key(op.f('exams_owner_id_fkey'), 'exams', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_exams_is_locked'), table_name='exams')
    op.drop_index(op.f('ix_exams_is_archived'), table_name='exams')
    op.drop_index(op.f('ix_exams_deleted_at'), table_name='exams')
    op.alter_column('exams', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('exams', 'deleted_at')
    op.drop_column('exams', 'is_archived')
    op.drop_constraint(None, 'exam_questions', type_='foreignkey')
    op.drop_constraint(None, 'exam_questions', type_='foreignkey')
    op.create_foreign_key(op.f('exam_questions_exam_id_fkey'), 'exam_questions', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('exam_questions_question_id_fkey'), 'exam_questions', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_exam_questions_deleted_at'), table_name='exam_questions')
    op.drop_column('exam_questions', 'deleted_at')
    op.drop_column('exam_questions', 'allow_peer_review')
    op.drop_constraint(None, 'answer_grading_histories', type_='foreignkey')
    op.drop_constraint(None, 'answer_grading_histories', type_='foreignkey')
    op.create_foreign_key(op.f('answer_grading_histories_teacher_id_fkey'), 'answer_grading_histories', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('answer_grading_histories_answer_id_fkey'), 'answer_grading_histories', 'student_answers', ['answer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_answer_grading_histories_deleted_at'), table_name='answer_grading_histories')
    op.drop_column('answer_grading_histories', 'deleted_at')
    op.drop_index(op.f('ix_interaction_likes_id'), table_name='interaction_likes')
    op.drop_index(op.f('ix_interaction_likes_deleted_at'), table_name='interaction_likes')
    op.drop_table('interaction_likes')
    op.drop_index(op.f('ix_interaction_comments_id'), table_name='interaction_comments')
    op.drop_index(op.f('ix_interaction_comments_deleted_at'), table_name='interaction_comments')
    op.drop_table('interaction_comments')
    # ### end Alembic commands ###
