"""rename_record_date_to_record_at_datetime

Revision ID: d8fadf274ef3
Revises: ee9cb75f7ca1
Create Date: 2026-04-08 17:29:51.202180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fadf274ef3'
down_revision: Union[str, Sequence[str], None] = 'ee9cb75f7ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_submissions', sa.Column('record_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('student_submissions', 'record_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_submissions', sa.Column('record_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False))
    op.drop_column('student_submissions', 'record_at')
    # ### end Alembic commands ###
