"""add_grading_history_and_exam_scores

Revision ID: ee9cb75f7ca1
Revises: b4536a1005b2
Create Date: 2026-04-08 08:39:59.061781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9cb75f7ca1'
down_revision: Union[str, Sequence[str], None] = 'b4536a1005b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_grading_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('old_score', sa.Integer(), nullable=True),
    sa.Column('new_score', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['student_answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_grading_histories_id'), 'answer_grading_histories', ['id'], unique=False)
    op.add_column('exam_questions', sa.Column('score', sa.Integer(), server_default='10', nullable=False))
    op.add_column('questions', sa.Column('needs_manual_grading', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('student_submissions', sa.Column('record_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_submissions', 'record_date')
    op.drop_column('questions', 'needs_manual_grading')
    op.drop_column('exam_questions', 'score')
    op.drop_index(op.f('ix_answer_grading_histories_id'), table_name='answer_grading_histories')
    op.drop_table('answer_grading_histories')
    # ### end Alembic commands ###
