services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 10
  seaweedfs-master:
    image: chrislusf/seaweedfs
    ports:
      - "19333:19333"
    command: "master -ip=seaweedfs-master -port=9333 -mdir=/data"
    volumes:
      - ./seaweedfs/master:/data
    restart: unless-stopped
  seaweedfs-volume:
    image: chrislusf/seaweedfs
    ports:
      - "18081:18081"
    command: "volume -mserver=seaweedfs-master:9333 -ip=seaweedfs-volume -port=8081 -dir=/data"
    depends_on:
      - seaweedfs-master
    volumes:
      - ./seaweedfs/volume:/data
    restart: unless-stopped
  backend:
    build:  ./backend
    ports:
      - "18080:18080"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SEAWEEDFS_MASTER_URL=${SEAWEEDFS_MASTER_URL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 18080 --reload"
  frontend:
    build: ./frontend
    ports:
      - "8088:80"
    environment:
      - SEAWEEDFS_VOLUME_URL=${SEAWEEDFS_VOLUME_URL}
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/cache:/var/cache/nginx
    depends_on:
      - backend
      - seaweedfs-volume
    restart: unless-stopped
